[server]
enableStaticServing = true

[theme]
primaryColor = "#DA70D6"  # Color de botones y elementos interactivos
backgroundColor = "#E6E6FA"  # Color de fondo
secondaryBackgroundColor = "#D8BFD8"  # Color de la barra lateral (tono lila claro)
textColor = "#000000"  # Color del texto
font = "sans serif"  # Tipo de fuente para toda la aplicación
